#!/bin/bash

APPDIR="$(
    cd "$(dirname "$0")" >/dev/null 2>&1
    pwd -P
)"

CONFDIR="$(
    cd ~
    pwd -P
)"

mkdir ~/.config/proxy-linux/ -p
cd ~/.config/proxy-linux/

NONE="FALSE"
COMMONPROXY="FALSE"
REMOVECONFS="FALSE"

if [ -f none ] && [ -f commonProxy ]; then
    NONE=$(cat none)
    COMMONPROXY=$(cat commonProxy)
else
    NONE="TRUE"
fi

choice=$(
    zenity --list --radiolist --width=350 --title="Configurações de proxy" \
        --text="Qual configuração de Proxy deseja utilizar:" \
        --column="" \
        --column="" \
        --separator=':' \
        $NONE "Nenhuma" \
        $COMMONPROXY "Proxy Comum/Autenticada" \
        $REMOVECONFS "Remover Configurações do Proxy"
)

case $choice in
"Nenhuma")
    echo "TRUE" >none
    echo "FALSE" >commonProxy
    hasProxy="FALSE"
    ;;
"Proxy Comum/Autenticada")
    echo "FALSE" >none
    echo "TRUE" >commonProxy
    hasProxy="TRUE"
    if [ ! -f ~/.config/proxy-linux/host ]; then
        $APPDIR/makeconf
    fi
    host=$(cat ~/.config/proxy-linux/host)
    port=$(cat ~/.config/proxy-linux/port)
    user=$(cat ~/.config/proxy-linux/user)
    pass=$(cat ~/.config/proxy-linux/pass)
    ;;
"Remover Configurações do Proxy")
    rm -rf ~/.config/proxy-linux/
    zenity --info --width=300 --text "Configurações Removidas! Você precisa executar novamente!"
    exit
    ;;
*)
    exit
    ;;
esac

if [ "$choice" == "Nenhuma" ] || [ "$choice" == "Proxy Comum/Autenticada" ]; then
    items=$(
        zenity --list --checklist --title="Proxy-Linux" \
            --height=260 \
            --text="Quais programas deseja mudar?" \
            --column="" \
            --column="" \
            --separator=':' \
            TRUE "Firefox" \
            TRUE "Chrome" \
            TRUE "Chromium" \
            TRUE "Wget" \
            TRUE "Profile" \
            TRUE "Apt"
    )
fi

if [ -f ~/.config/proxy-linux/auth ]; then
    httpProxyStr="http_proxy=http://$user:$pass@$host:$port"
    httpsProxyStr="https_proxy=http://$user:$pass@$host:$port"
    ftpProxyStr="ftp_proxy=http://$user:$pass@$host:$port"
else
    httpProxyStr="http_proxy=http://$host:$port"
    httpsProxyStr="https_proxy=http://$host:$port"
    ftpProxyStr="ftp_proxy=http://$host:$port"
fi

# FIREFOX
if [[ $items == *"Firefox"* ]]; then
    cat ~/.mozilla/firefox/profiles.ini | grep Path= | cut -d= -f2 >/tmp/profilesDirFox
    while read DIRFOX; do
        if [ -f ~/.mozilla/firefox/$DIRFOX/prefs.js ]; then
            perfile=~/.mozilla/firefox/$DIRFOX/prefs.js
            if [ $hasProxy == "TRUE" ]; then
                #Firefox TYPE
                if [ "$(grep '"network.proxy.type"' $perfile)" == "" ]; then
                    echo 'user_pref("network.proxy.type", 1);' >>$perfile
                else
                    sed -i "/\"network.proxy.type\"/c\user_pref(\"network.proxy.type\", 1);" $perfile
                fi
                #Firefox SHARED
                if [ "$(grep '"network.proxy.share_proxy_settings"' $perfile)" == "" ]; then
                    echo 'user_pref("network.proxy.share_proxy_settings", true);' >>$perfile
                else
                    sed -i "/\"network.proxy.share_proxy_settings\"/c\user_pref(\"network.proxy.share_proxy_settings\", true);" $perfile
                fi
                #Firefox HOST
                if [ "$(grep '"network.proxy.http"' $perfile)" == "" ]; then
                    echo "user_pref(\"network.proxy.http\", \"$host\");" >>$perfile
                else
                    sed -i "/\"network.proxy.http\"/c\user_pref(\"network.proxy.http\", \"$host\");" $perfile
                fi
                #Firefox PORT
                if [ "$(grep '"network.proxy.http_port"' $perfile)" == "" ]; then
                    echo "user_pref(\"network.proxy.http_port\", $port);" >>$perfile
                else
                    sed -i "/\"network.proxy.http_port\"/c\user_pref(\"network.proxy.http_port\", $port);" $perfile
                fi
            else
                #Firefox TYPE
                if [ "$(grep '"network.proxy.type"' $perfile)" == "" ]; then
                    echo 'user_pref("network.proxy.type", 0);' >>$perfile
                else
                    sed -i "/\"network.proxy.type\"/c\user_pref(\"network.proxy.type\", 0);" $perfile
                fi
            fi
        fi
    done </tmp/profilesDirFox
fi

# WGET
if [[ $items == *"Wget"* ]]; then
    if [ $hasProxy == "TRUE" ]; then
        echo "use_proxy=yes" >~/.wgetrc
        echo "$httpProxyStr" >>~/.wgetrc
        echo "$httpsProxyStr" >>~/.wgetrc
        echo "$ftpProxyStr" >>~/.wgetrc
    else
        echo "#PROXY-LINUX ALTEROU ESSE ARQUIVO! Use ele para modificar!" >~/.wgetrc
    fi
fi

# PROFILE
if [[ $items == *"Profile"* ]]; then
    if [ $hasProxy == "TRUE" ]; then
        if [ "$(grep 'http_proxy' $HOME/.profile)" == "" ]; then
            echo "export $httpProxyStr" >>~/.profile
            echo "export $httpsProxyStr" >>~/.profile
            echo "export $ftpProxyStr" >>~/.profile
        else
            sed -i "/http_proxy/c\export $httpProxyStr" ~/.profile
            sed -i "/https_proxy/c\export $httpsProxyStr" ~/.profile
            sed -i "/ftp_proxy/c\export $ftpProxyStr" ~/.profile
        fi
    else
        sed -i "/http_proxy/d" ~/.profile
        sed -i "/https_proxy/d" ~/.profile
        sed -i "/ftp_proxy/d" ~/.profile
    fi
fi

# CHROME
if [[ $items == *"Chrome"* ]]; then
    if [ $hasProxy == "TRUE" ]; then
        pkexec $APPDIR/supermain "Chrome" "PROXY" "$CONFDIR"
    else
        pkexec $APPDIR/supermain "Chrome" "NOPROXY" "$CONFDIR"
    fi
fi

# CHROMIUM
if [[ $items == *"Chromium"* ]]; then
    if [ $hasProxy == "TRUE" ]; then
        pkexec $APPDIR/supermain "Chromium" "PROXY" "$CONFDIR"
    else
        pkexec $APPDIR/supermain "Chromium" "NOPROXY" "$CONFDIR"
    fi
fi

# APT
if [[ $items == *"Apt"* ]]; then
    if [ $hasProxy == "TRUE" ]; then
        pkexec $APPDIR/supermain "Apt" "PROXY" "$CONFDIR"
    else
        pkexec $APPDIR/supermain "Apt" "NOPROXY" "$CONFDIR"
    fi
fi

zenity --info --width=350 --text "Novas configurações adicionadas com sucesso! \n\nPara alguns apps especificos você deve reiniciar!"
