#!/bin/bash

cd /usr/proxy-linux/

escolha=$(
zenity --list --radiolist --title="Configurações de proxy" \
--text="Qual configuração de Proxy deseja utilizar:" \
--column="" \
--column="" \
--separator=':' \
FALSE "Nenhuma" \
TRUE  "Proxy Comum/Autenticada" \
FALSE "Remover Configurações do Proxy"
)

if [ "$escolha" == "Nenhuma" ] || [ "$escolha" == "Proxy Comum/Autenticada" ]; then
	itens=$(
	zenity --list --checklist --title="Proxy-Linux" \
	--height=260 \
	--text="Quais programas deseja mudar?" \
	--column="" \
	--column="" \
	--separator=':' \
	TRUE "Firefox" \
	TRUE "Chrome" \
	TRUE "Chromium" \
	TRUE "Apt" \
	TRUE "Wget" \
	TRUE "Profile"
	)
	perfile=~/.mozilla/firefox/$(cat ~/.mozilla/firefox/profiles.ini | grep Path= | cut -d= -f2)/prefs.js
fi

case $escolha in
	"Nenhuma")
		if [[ $itens == *"Firefox"* ]]; then
			#Firefox TYPE
			if [ "$(grep '"network.proxy.type"' $perfile)" == "" ]; then
				echo 'user_pref("network.proxy.type", 0);' >> $perfile
			else
				sed -i "/\"network.proxy.type\"/c\user_pref(\"network.proxy.type\", 0);" $perfile
			fi
		fi
		if [[ $itens == *"Wget"* ]]; then
			echo "#PROXY-LINUX ALTEROU ESSE ARQUIVO! Use ele para modificar!" > ~/.wgetrc
		fi
		if [[ $itens == *"Profile"* ]]; then
			sed -i "/http_proxy/d" ~/.profile
			sed -i "/https_proxy/d" ~/.profile
			sed -i "/ftp_proxy/d" ~/.profile
		fi
	;;
	"Proxy Comum/Autenticada")
		if [ ! -f ~/.config/proxy-linux/host ]; then
			./makeconf
		fi
		host=$(cat ~/.config/proxy-linux/host)
		port=$(cat ~/.config/proxy-linux/port)
		user=$(cat ~/.config/proxy-linux/user)
		pass=$(cat ~/.config/proxy-linux/pass)

		if [[ $itens == *"Firefox"* ]]; then
			#Firefox TYPE
			if [ "$(grep '"network.proxy.type"' $perfile)" == "" ]; then
				echo 'user_pref("network.proxy.type", 1);' >> $perfile
			else
				sed -i "/\"network.proxy.type\"/c\user_pref(\"network.proxy.type\", 1);" $perfile
			fi
			#Firefox SHARED
			if [ "$(grep '"network.proxy.share_proxy_settings"' $perfile)" == "" ]; then
				echo 'user_pref("network.proxy.share_proxy_settings", true);' >> $perfile
			else
				sed -i "/\"network.proxy.share_proxy_settings\"/c\user_pref(\"network.proxy.share_proxy_settings\", true);" $perfile
			fi
			#Firefox HOST
			if [ "$(grep '"network.proxy.http"' $perfile)" == "" ]; then
				echo "user_pref(\"network.proxy.http\", \"$host\");" >> $perfile
			else
				sed -i "/\"network.proxy.http\"/c\user_pref(\"network.proxy.http\", \"$host\");" $perfile
			fi
			#Firefox PORT
			if [ "$(grep '"network.proxy.http_port"' $perfile)" == "" ]; then
				echo "user_pref(\"network.proxy.http_port\", $port);" >> $perfile
			else
				sed -i "/\"network.proxy.http_port\"/c\user_pref(\"network.proxy.http_port\", $port);" $perfile
			fi			
		fi

		if [ -f ~/.config/proxy-linux/auth ]; then
			httpProxyStr="http_proxy=http://$user:$pass@$host:$port"
			httpsProxyStr="https_proxy=https://$user:$pass@$host:$port"
			ftpProxyStr="ftp_proxy=ftp://$user:$pass@$host:$port"
		else
			httpProxyStr="http_proxy=http://$host:$port"
			httpsProxyStr="https_proxy=https://$host:$port"
			ftpProxyStr="ftp_proxy=ftp://$host:$port"
		fi

		if [[ $itens == *"Wget"* ]]; then
			echo "use_proxy=yes" > ~/.wgetrc
			echo "$httpProxyStr" >> ~/.wgetrc
			echo "$httpsProxyStr" >> ~/.wgetrc
			echo "$ftpProxyStr" >> ~/.wgetrc
		fi

		if [[ $itens == *"Profile"* ]]; then
			if [ "$(grep 'http_proxy' $HOME/.profile)" == "" ]; then
				echo "export $httpProxyStr" >> ~/.profile
				echo "export $httpsProxyStr" >> ~/.profile
				echo "export $ftpProxyStr" >> ~/.profile
			else
				sed -i "/http_proxy/c\export $httpProxyStr" ~/.profile
				sed -i "/https_proxy/c\export $httpsProxyStr" ~/.profile
				sed -i "/ftp_proxy/c\export $ftpProxyStr" ~/.profile
			fi
		fi

	;;
	"Remover Configurações do Proxy")
		cd ~/.config/proxy-linux/
		rm host port auth pass user
		cd -
		zenity --info --text "Configurações Removidas! Você precisa executar novamente!"
		exit
	;;
	*)
		echo "saindo..."
		exit
	;;
esac

saidaSuper=$(pkexec $(pwd)/supermain "$escolha" "$itens" "$(echo ~)")

while [[ $saidaSuper != *"GKSU_SUCCESS"* ]]; do
	zenity --info --text "Senha incorreta! Tente novamente!"
	saidaSuper=$(pkexec $(pwd)/supermain "$escolha" "$itens" "$(echo ~)")
done

zenity --info --width=350 --text "Novas configurações adicionadas com sucesso! \n\nPara alguns apps especificos você deve reiniciar!"
