#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
    rm -rf "$BASEDIR/Desktop/proxy-linux-sc.desktop"
    rm -rf "$BASEDIR/Área de Trabalho/proxy-linux-sc.desktop"
done < /tmp/homes.list