#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

function geraShort {
	echo "[Desktop Entry]"
	echo "Type=Link"
	cat $1 | \
	grep "Name=" | head -n1
	cat $1 | \
	grep "Name[pt_BR]=" | head -n1
	cat $1 | \
	grep "Icon=" | head -n1
	echo "URL=$2"
}

while read USUARIO; do
	geraShort /usr/share/applications/proxy-linux.desktop \
	/usr/share/applications/proxy-linux.desktop \
	> /home/$USUARIO/Desktop/proxy-linux-sc.desktop
	geraShort /usr/share/applications/proxy-linux.desktop \
	/usr/share/applications/proxy-linux.desktop \
	> /home/$USUARIO/Área\ de\ Trabalho/proxy-linux-sc.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list
